/**
 * Config Generator for CLIProxyAPI
 *
 * Generates config.yaml for CLIProxyAPI based on provider.
 * Handles OAuth token paths and provider-specific settings.
 */

import * as fs from 'fs';
import * as path from 'path';
import { getCcsDir } from '../utils/config-manager';
import { CLIProxyProvider, ProviderConfig, ProviderModelMapping } from './types';

/** Default CLIProxy port */
export const CLIPROXY_DEFAULT_PORT = 8317;

/** Internal API key for CCS-managed requests */
const CCS_INTERNAL_API_KEY = 'ccs-internal-managed';

/**
 * Provider configurations with model mappings
 */
export const PROVIDER_CONFIGS: Record<CLIProxyProvider, ProviderConfig> = {
  gemini: {
    name: 'gemini',
    displayName: 'Gemini',
    models: {
      defaultModel: 'gemini-2.5-pro',
      claudeModel: 'gemini-2.5-pro',
      opusModel: 'gemini-3-pro-preview',
      sonnetModel: 'gemini-2.5-pro',
      haikuModel: 'gemini-2.5-flash',
    },
    requiresOAuth: true,
  },
  codex: {
    name: 'codex',
    displayName: 'Codex',
    models: {
      defaultModel: 'gpt-5.1-codex-max',
      claudeModel: 'gpt-5.1-codex-max',
      opusModel: 'gpt-5.1-codex-max-high',
      sonnetModel: 'gpt-5.1-codex-max',
      haikuModel: 'gpt-5.1-codex-mini-high',
    },
    requiresOAuth: true,
  },
  qwen: {
    name: 'qwen',
    displayName: 'Qwen',
    models: {
      defaultModel: 'qwen-max',
      claudeModel: 'qwen-max',
      opusModel: 'qwen-max',
      sonnetModel: 'qwen-plus',
      haikuModel: 'qwen-turbo',
    },
    requiresOAuth: true,
  },
};

/**
 * Get provider configuration
 */
export function getProviderConfig(provider: CLIProxyProvider): ProviderConfig {
  const config = PROVIDER_CONFIGS[provider];
  if (!config) {
    throw new Error(`Unknown provider: ${provider}`);
  }
  return config;
}

/**
 * Get model mapping for provider
 */
export function getModelMapping(provider: CLIProxyProvider): ProviderModelMapping {
  return getProviderConfig(provider).models;
}

/**
 * Get CLIProxy base directory
 * All CLIProxy-related files are stored under ~/.ccs/cliproxy/
 */
export function getCliproxyDir(): string {
  return path.join(getCcsDir(), 'cliproxy');
}

/**
 * Get auth directory for provider
 * All providers use a FLAT auth directory structure for unified config.
 * CLIProxyAPI stores OAuth tokens directly in auth/ (not subdirectories).
 * This enables all providers to be discovered and used concurrently.
 */
export function getProviderAuthDir(_provider: CLIProxyProvider): string {
  // Use flat structure - all auth files in same directory for unified discovery
  // Provider param kept for API compatibility (CLIProxyAPI handles via auth file type field)
  return path.join(getCliproxyDir(), 'auth');
}

/**
 * Get base auth directory for CLIProxyAPI
 */
export function getAuthDir(): string {
  return path.join(getCliproxyDir(), 'auth');
}

/**
 * Get config file path
 */
export function getConfigPath(): string {
  return path.join(getCliproxyDir(), 'config.yaml');
}

/**
 * Get binary directory path
 */
export function getBinDir(): string {
  return path.join(getCliproxyDir(), 'bin');
}

/**
 * Generate UNIFIED config.yaml content for ALL providers
 * This enables concurrent usage of gemini/codex/qwen without config conflicts.
 * CLIProxyAPI routes requests by model name to the appropriate provider.
 */
function generateUnifiedConfigContent(port: number = CLIPROXY_DEFAULT_PORT): string {
  const authDir = getAuthDir(); // Base auth dir - CLIProxyAPI scans subdirectories

  // Unified config with all providers
  const config = `# CLIProxyAPI unified config generated by CCS
# Supports: gemini, codex, qwen (concurrent usage)
# Generated: ${new Date().toISOString()}

port: ${port}
debug: false
logging-to-file: false
usage-statistics-enabled: false

# CCS internal authentication
api-keys:
  - "${CCS_INTERNAL_API_KEY}"

# OAuth tokens stored in subdirectories (gemini/, codex/, qwen/)
# CLIProxyAPI auto-discovers auth files in subdirectories
auth-dir: "${authDir}"

# All providers configured - routes by model name
# No provider-specific sections needed - OAuth auth files provide credentials
`;

  return config;
}

/**
 * Generate unified config.yaml file (supports all providers concurrently)
 * Only regenerates if config doesn't exist.
 * @returns Path to config file
 */
export function generateConfig(
  provider: CLIProxyProvider,
  port: number = CLIPROXY_DEFAULT_PORT
): string {
  const configPath = getConfigPath();

  // Ensure provider auth directory exists
  const authDir = getProviderAuthDir(provider);
  fs.mkdirSync(path.dirname(configPath), { recursive: true });
  fs.mkdirSync(authDir, { recursive: true, mode: 0o700 });

  // Only generate config if it doesn't exist (unified config serves all providers)
  if (!fs.existsSync(configPath)) {
    const configContent = generateUnifiedConfigContent(port);
    fs.writeFileSync(configPath, configContent, { mode: 0o600 });
  }

  return configPath;
}

/**
 * Check if config exists for provider
 */
export function configExists(): boolean {
  return fs.existsSync(getConfigPath());
}

/**
 * Delete config file
 */
export function deleteConfig(): void {
  const configPath = getConfigPath();
  if (fs.existsSync(configPath)) {
    fs.unlinkSync(configPath);
  }
}

/**
 * Get environment variables for Claude CLI
 * Uses provider-specific endpoint (e.g., /api/provider/gemini) for explicit routing.
 * This enables concurrent gemini/codex usage - each session routes to its provider via URL path.
 */
export function getClaudeEnvVars(
  provider: CLIProxyProvider,
  port: number = CLIPROXY_DEFAULT_PORT
): NodeJS.ProcessEnv {
  const models = getModelMapping(provider);

  return {
    // Provider-specific endpoint - routes to correct provider via URL path
    ANTHROPIC_BASE_URL: `http://127.0.0.1:${port}/api/provider/${provider}`,
    ANTHROPIC_AUTH_TOKEN: CCS_INTERNAL_API_KEY,
    ANTHROPIC_MODEL: models.claudeModel,
    ANTHROPIC_DEFAULT_OPUS_MODEL: models.opusModel || models.claudeModel,
    ANTHROPIC_DEFAULT_SONNET_MODEL: models.sonnetModel || models.claudeModel,
    ANTHROPIC_DEFAULT_HAIKU_MODEL: models.haikuModel || models.claudeModel,
  };
}
